export const UPDATE_VALUE = 'UPDATE_VALUE';
export const ACTIVATE_WARNING = 'ACTIVATE_WARNING';
export const OPEN_CALC_WINDOW = 'OPEN_CALC_WINDOW';
export const ACTIVATE_FIRST_BTN = 'ACTIVATE_FIRST_BTN';
export const ACTIVATE_SECOND_BTN = 'ACTIVATE_SECOND_BTN';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';